version: "3.6"
services:
  registration-api:
    build:
      context: ./
    depends_on:
      - postgres
      - rabbitmq
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/amqp
      - SPRING_RABBITMQ_HOST=rabbitmq
    networks:
      - amqp-network
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: amqp
      POSTGRES_PASSWORD: amqp
      POSTGRES_DB: amqp
    ports:
      - "5432:5432"
    networks:
      - amqp-network
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - amqp-network

networks:
  amqp-network:
    external: true